
import Footer from "./components/Footer";
import Navbarin from "./components/Navbar";
import "./globals.css";



export const metadata = {
  title: "Cooking Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Navbarin/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
